apiVersion: entity.accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: hello
  tags:
    - hello
    - getting-started
  title: Hello World
  description: Contains just a README
spec:
  accelerator:
    iconUrl: https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/HelloWorld.svg/1024px-HelloWorld.svg.png