apiVersion: entity.accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: bs-hello-acc
  tags:
    - simple
    - getting-started
    - test
  title: Backstage Test Accelerator - Hello
  description: testing acc flow in BS mode
spec:
  accelerator:
    iconUrl: https://images.freecreatives.com/wp-content/uploads/2015/05/smiley-559124_640.jpg
    options:
      - name: testOption
        label: are you excited about TAP 1.7.0?
        inputType: select
        choices:
          - value: "yes1"
            text: Yes!
          - value: "very"
            text: I'm indeed very excited!
        defaultValue: "yes1"
    imports:
      - name: bs-hello-frag
  engine:
    chain:
      - merge:
          - include: ["**/*"]
          - type: InvokeFragment
            reference: bs-hello-frag